kind: pipeline
name: default

steps:
  
- name: Packet CSI Helm Chart
  image: alpine
  environment:
    auth_token:
      from_secret: auth_token
    project_id:
      from_secret: project_id
  commands:
  - apk --update add curl docker
  - curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.5.1/kind-linux-amd64
  - chmod +x ./kind
  - ./kind create cluster --name packet-csi-$DRONE_COMMIT && export KUBECONFIG="$(./kind get kubeconfig-path)"
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
  - chmod +x kubectl 
  - mv kubectl /usr/local/bin/kubectl
  - export PATH=$PATH:/usr/local/bin
  - sed -e "s|API_KEY|$auth_token|g" -e "s|PROJECT_ID|$project_id|g" scripts/secret.template | tee sec.yaml > /dev/null
  - kubectl create -f sec.yaml
  - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh ; chmod 700 get_helm.sh ; ./get_helm.sh
  - helm install --debug --generate-name --dry-run ./packet-csi
